import type { RewardCurrency, RewardRule, RotatingProgram } from "./types";

export interface CatalogCard {
  id: string;
  issuer: string;
  name: string;
  matchPatterns: RegExp[];
  currency: RewardCurrency;
  programName?: string;
  defaultCentsPerPoint: number;
  baseRate: number;
  rules: RewardRule[];
  rotating?: RotatingProgram;
  verifiedAsOf: string;
}

// Rates come from each issuer's public rewards page. Portal-only and single-merchant
// bonuses (Chase Travel, Amazon, Lyft, ...) are left out since they don't map to a
// category. Shared caps are applied to each category because rules can't share a cap.
const VERIFIED = "2026-09";

const yearCap = (amount: number) => ({ amount, period: "YEAR" as const });

export const CATALOG: CatalogCard[] = [
  {
    id: "chase-freedom-flex",
    issuer: "Chase",
    name: "Freedom Flex",
    matchPatterns: [/freedom\s*flex/i],
    currency: "CASH",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "DRUGSTORES", rate: 3 },
    ],
    rotating: {
      rate: 5,
      capAmount: 1500,
      quarters: [
        { year: 2026, quarter: 1, categories: ["DINING"] },
        { year: 2026, quarter: 2, categories: ["ONLINE_SHOPPING", "TRAVEL"] },
        { year: 2026, quarter: 3, categories: ["GAS", "TRANSIT", "EV_CHARGING", "ENTERTAINMENT"] },
        { year: 2026, quarter: 4, categories: ["GROCERIES", "DINING"] },
      ],
    },
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-freedom-unlimited",
    issuer: "Chase",
    name: "Freedom Unlimited",
    matchPatterns: [/freedom\s*unlimited/i],
    currency: "CASH",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "DRUGSTORES", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-sapphire-preferred",
    issuer: "Chase",
    name: "Sapphire Preferred",
    matchPatterns: [/sapphire\s*preferred/i],
    currency: "POINTS",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "STREAMING", rate: 3 },
      { category: "GAS", rate: 3 },
      { category: "EV_CHARGING", rate: 3 },
      { category: "TRAVEL", rate: 2 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-sapphire-reserve",
    issuer: "Chase",
    name: "Sapphire Reserve",
    matchPatterns: [/sapphire\s*reserve/i],
    currency: "POINTS",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "TRAVEL", rate: 4 },
      { category: "DINING", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-amazon-prime-visa",
    issuer: "Chase",
    name: "Prime Visa",
    matchPatterns: [/prime\s*visa/i, /amazon.*prime/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 2 },
      { category: "GAS", rate: 2 },
      { category: "TRANSIT", rate: 2 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-ink-business-cash",
    issuer: "Chase",
    name: "Ink Business Cash",
    matchPatterns: [/ink\s*(business\s*)?cash/i],
    currency: "CASH",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "UTILITIES", rate: 5, cap: yearCap(25000) },
      { category: "GAS", rate: 2, cap: yearCap(25000) },
      { category: "DINING", rate: 2, cap: yearCap(25000) },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-ink-business-unlimited",
    issuer: "Chase",
    name: "Ink Business Unlimited",
    matchPatterns: [/ink\s*(business\s*)?unlimited/i],
    currency: "CASH",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "chase-ink-business-preferred",
    issuer: "Chase",
    name: "Ink Business Preferred",
    matchPatterns: [/ink\s*(business\s*)?preferred/i],
    currency: "POINTS",
    programName: "Chase Ultimate Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "TRAVEL", rate: 3, cap: yearCap(150000) },
      { category: "UTILITIES", rate: 3, cap: yearCap(150000) },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "amex-gold",
    issuer: "American Express",
    name: "Gold Card",
    matchPatterns: [/(amex|american\s*express)(?!.*business).*\bgold\b/i],
    currency: "POINTS",
    programName: "Amex Membership Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 4, cap: yearCap(50000) },
      { category: "GROCERIES", rate: 4, cap: yearCap(25000) },
      { category: "TRAVEL", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "amex-platinum",
    issuer: "American Express",
    name: "Platinum Card",
    matchPatterns: [/(amex|american\s*express)(?!.*business).*\bplatinum\b/i],
    currency: "POINTS",
    programName: "Amex Membership Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [{ category: "TRAVEL", rate: 5, cap: yearCap(500000) }],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "amex-green",
    issuer: "American Express",
    name: "Green Card",
    matchPatterns: [/(amex|american\s*express).*\bgreen\b/i],
    currency: "POINTS",
    programName: "Amex Membership Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "TRAVEL", rate: 3 },
      { category: "TRANSIT", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "amex-blue-cash-preferred",
    issuer: "American Express",
    name: "Blue Cash Preferred",
    matchPatterns: [/blue\s*cash\s*preferred/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "GROCERIES", rate: 6, cap: yearCap(6000) },
      { category: "STREAMING", rate: 6 },
      { category: "TRANSIT", rate: 3 },
      { category: "GAS", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "amex-blue-cash-everyday",
    issuer: "American Express",
    name: "Blue Cash Everyday",
    matchPatterns: [/blue\s*cash\s*everyday/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "GROCERIES", rate: 3, cap: yearCap(6000) },
      { category: "ONLINE_SHOPPING", rate: 3, cap: yearCap(6000) },
      { category: "GAS", rate: 3, cap: yearCap(6000) },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "citi-double-cash",
    issuer: "Citi",
    name: "Double Cash",
    matchPatterns: [/double\s*cash/i],
    currency: "CASH",
    programName: "Citi ThankYou",
    defaultCentsPerPoint: 1,
    baseRate: 2,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "citi-strata-premier",
    issuer: "Citi",
    name: "Strata Premier",
    matchPatterns: [/strata\s*premier/i],
    currency: "POINTS",
    programName: "Citi ThankYou",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "TRAVEL", rate: 3 },
      { category: "DINING", rate: 3 },
      { category: "GROCERIES", rate: 3 },
      { category: "GAS", rate: 3 },
      { category: "EV_CHARGING", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "citi-costco-anywhere-visa",
    issuer: "Citi",
    name: "Costco Anywhere Visa",
    matchPatterns: [/costco/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "GAS", rate: 4, cap: yearCap(7000) },
      { category: "EV_CHARGING", rate: 4, cap: yearCap(7000) },
      { category: "DINING", rate: 3 },
      { category: "TRAVEL", rate: 3 },
      { category: "WAREHOUSE_CLUBS", rate: 2 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "capital-one-savor",
    issuer: "Capital One",
    name: "Savor",
    matchPatterns: [/\bsavor/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "ENTERTAINMENT", rate: 3 },
      { category: "STREAMING", rate: 3 },
      { category: "GROCERIES", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "capital-one-venture-x",
    issuer: "Capital One",
    name: "Venture X",
    matchPatterns: [/venture\s*x\b/i],
    currency: "MILES",
    programName: "Capital One Miles",
    defaultCentsPerPoint: 1,
    baseRate: 2,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "capital-one-venture",
    issuer: "Capital One",
    name: "Venture",
    matchPatterns: [/venture(?!\s*(x\b|one))/i],
    currency: "MILES",
    programName: "Capital One Miles",
    defaultCentsPerPoint: 1,
    baseRate: 2,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "capital-one-quicksilver",
    issuer: "Capital One",
    name: "Quicksilver",
    matchPatterns: [/quicksilver/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "discover-it-cash-back",
    issuer: "Discover",
    name: "it Cash Back",
    matchPatterns: [/discover\s*it(?!\s*(miles|chrome))/i, /discover\s*cash\s*back/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [],
    rotating: {
      rate: 5,
      capAmount: 1500,
      quarters: [
        { year: 2026, quarter: 1, categories: ["GROCERIES", "WAREHOUSE_CLUBS", "STREAMING"] },
        { year: 2026, quarter: 2, categories: ["DINING", "HOME_IMPROVEMENT"] },
        { year: 2026, quarter: 3, categories: ["GAS", "TRANSIT", "DRUGSTORES"] },
        { year: 2026, quarter: 4, categories: ["DINING", "ENTERTAINMENT", "UTILITIES"] },
      ],
    },
    verifiedAsOf: VERIFIED,
  },
  {
    id: "discover-it-miles",
    issuer: "Discover",
    name: "it Miles",
    matchPatterns: [/discover\s*it\s*miles/i],
    currency: "MILES",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "wells-fargo-active-cash",
    issuer: "Wells Fargo",
    name: "Active Cash",
    matchPatterns: [/active\s*cash/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 2,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "wells-fargo-autograph",
    issuer: "Wells Fargo",
    name: "Autograph",
    matchPatterns: [/autograph(?!\s*journey)/i],
    currency: "POINTS",
    programName: "Wells Fargo Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "TRAVEL", rate: 3 },
      { category: "GAS", rate: 3 },
      { category: "TRANSIT", rate: 3 },
      { category: "STREAMING", rate: 3 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "bofa-unlimited-cash-rewards",
    issuer: "Bank of America",
    name: "Unlimited Cash Rewards",
    matchPatterns: [/unlimited\s*cash\s*rewards/i],
    currency: "CASH",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "bofa-travel-rewards",
    issuer: "Bank of America",
    name: "Travel Rewards",
    matchPatterns: [/(bank\s*of\s*america|bofa|boa)\b.*travel\s*rewards/i],
    currency: "POINTS",
    defaultCentsPerPoint: 1,
    baseRate: 1.5,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "us-bank-altitude-go",
    issuer: "U.S. Bank",
    name: "Altitude Go",
    matchPatterns: [/altitude\s*go/i],
    currency: "POINTS",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 4, cap: { amount: 2000, period: "QUARTER" } },
      { category: "GROCERIES", rate: 2 },
      { category: "GAS", rate: 2 },
      { category: "EV_CHARGING", rate: 2 },
      { category: "STREAMING", rate: 2 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "bilt-blue",
    issuer: "Bilt",
    name: "Blue",
    matchPatterns: [/bilt(?!.*(obsidian|palladium))/i],
    currency: "POINTS",
    programName: "Bilt Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
  {
    // 3x is on dining or groceries (cardholder's choice); dining is the default here.
    id: "bilt-obsidian",
    issuer: "Bilt",
    name: "Obsidian",
    matchPatterns: [/bilt.*obsidian/i],
    currency: "POINTS",
    programName: "Bilt Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 1,
    rules: [
      { category: "DINING", rate: 3 },
      { category: "TRAVEL", rate: 2 },
    ],
    verifiedAsOf: VERIFIED,
  },
  {
    id: "bilt-palladium",
    issuer: "Bilt",
    name: "Palladium",
    matchPatterns: [/bilt.*palladium/i],
    currency: "POINTS",
    programName: "Bilt Rewards",
    defaultCentsPerPoint: 1,
    baseRate: 2,
    rules: [],
    verifiedAsOf: VERIFIED,
  },
];

function matchName(name: string): CatalogCard | null {
  return CATALOG.find((card) => card.matchPatterns.some((p) => p.test(name))) ?? null;
}

export function matchCatalogCard(officialName: string | null, accountName: string): CatalogCard | null {
  return (officialName ? matchName(officialName) : null) ?? matchName(accountName);
}

export function findCatalogCard(id: string): CatalogCard | null {
  return CATALOG.find((c) => c.id === id) ?? null;
}
